/**
 * Search, retrieval, reranking, and context-assembly types.
 *
 * The retrieval service implements hybrid search (vector + keyword),
 * reranking, and context window assembly for RAG.
 *
 * @module search
 */

import type {
  DocumentId,
  Metadata,
  PaginationParams,
  Timestamp,
  WorkspaceId,
} from "./common.js";

// ─── Search Query ───────────────────────────────────────────────────────────

/**
 * A search query submitted to the retrieval service.
 */
export interface SearchQuery {
  /** Unique query identifier (generated by caller or service). */
  id: string;
  /** Workspace scope. */
  workspace_id: WorkspaceId;
  /** The natural-language query text. */
  query: string;
  /** Optional embedding of the query text (for vector search). */
  query_embedding?: number[];
  /** Maximum number of results to return. */
  top_k: number;
  /** Minimum similarity threshold (0.0–1.0). */
  similarity_threshold: number;
  /** Filters to narrow search scope. */
  filters: SearchFilters;
  /** Whether to use hybrid search (vector + keyword). */
  hybrid: boolean;
  /** Optional reranking configuration. */
  rerank?: RerankConfig;
  /** Query timestamp. */
  created_at: Timestamp;
}

/**
 * Filters applicable to a search query.
 */
export interface SearchFilters {
  /** Restrict to specific document IDs. */
  document_ids?: DocumentId[];
  /** Restrict to documents with matching tags. */
  tags?: string[];
  /** Restrict to documents created after this timestamp. */
  created_after?: Timestamp;
  /** Restrict to documents created before this timestamp. */
  created_before?: Timestamp;
  /** Arbitrary metadata field filters (key → value). */
  metadata?: Record<string, unknown>;
}

// ─── Search Result ──────────────────────────────────────────────────────────

/**
 * A single search result item (one chunk).
 */
export interface SearchResult {
  /** Rank position (1-based). */
  rank: number;
  /** The matched chunk. */
  chunk_id: string;
  /** Parent document. */
  document_id: DocumentId;
  /** The chunk text content. */
  text: string;
  /** Relevance score (range depends on the search backend). */
  score: number;
  /** Reranking-adjusted score (if reranking was applied). */
  rerank_score?: number;
  /** Source breakdown (e.g. vector=0.8, keyword=0.6). */
  source_scores?: SearchSourceScores;
  /** Chunk-level metadata. */
  metadata: Metadata;
}

/**
 * Per-source relevance scores for a hybrid search result.
 */
export interface SearchSourceScores {
  /** Vector similarity score. */
  vector?: number;
  /** Keyword / BM25 score. */
  keyword?: number;
}

// ─── Reranking ──────────────────────────────────────────────────────────────

/**
 * Configuration for result reranking.
 */
export interface RerankConfig {
  /** Reranker model identifier (e.g. "cohere", "cross-encoder"). */
  model: string;
  /** Number of top candidates to rerank (before picking top_k). */
  top_n: number;
}

/**
 * Reranking score assigned to a search result.
 */
export interface RerankingScore {
  /** The chunk being scored. */
  chunk_id: string;
  /** Original retrieval score. */
  initial_score: number;
  /** Score after reranking. */
  rerank_score: number;
  /** The reranker model used. */
  model: string;
}

// ─── Context Window ─────────────────────────────────────────────────────────

/**
 * An assembled context window – a group of ranked chunks formatted
 * into a single string for injection into an LLM prompt.
 */
export interface ContextWindow {
  /** Unique identifier for this context assembly. */
  id: string;
  /** The original query. */
  query_id: string;
  /** Workspace scope. */
  workspace_id: WorkspaceId;
  /** Ranked chunks included in the window. */
  chunks: ContextChunk[];
  /** Assembled text ready for prompt injection. */
  assembled_text: string;
  /** Total token count (estimated). */
  token_count: number;
  /** Maximum allowed token budget. */
  max_tokens: number;
  /** Assembly timestamp. */
  created_at: Timestamp;
}

/**
 * A single chunk within an assembled context window.
 */
export interface ContextChunk {
  /** The chunk identifier. */
  chunk_id: string;
  /** Document title (for citation). */
  document_title: string;
  /** Chunk text content. */
  text: string;
  /** Relevance score. */
  score: number;
  /** Position in the context window (0-based). */
  position: number;
}

// ─── Search Response ────────────────────────────────────────────────────────

/**
 * Response envelope for a search / retrieval request.
 */
export interface SearchResponse {
  /** The query that was executed. */
  query_id: string;
  /** Ranked results. */
  results: SearchResult[];
  /** Pagination info. */
  pagination: PaginationParams & { next_cursor: string | null };
  /** Total number of matching chunks (before top_k truncation). */
  total_hits: number;
  /** Query latency in milliseconds. */
  latency_ms: number;
}
